### PR TITLE
Project refactor ahead of merge

### PR DESCRIPTION
**Pull request by mattrpav**
* Package rename com.mediadriver.atlas -> io.atlasmap 
 * Removal of ".v2" from engine packages
 * Version bump to 1.11.5 ahead of big merge-down
 * Temporary removal of converters ahead of big merge-down (they've been merged in with atlas-core

### CODE REVIEW

**Comment by mattrpav** [comment]
Cancelling merge into syndesis repo.. going to merge into atlasmap

**Comment by rhuss** [comment]
Sorry for my ignorance, tbh I'm pretty new to the datamapper setup (and datamapper in general). What is the current status wrt to GitHub repos ? Where can I find what (ui parts, backend). 

How is the datamapper ui included in syndesis-ui ? // @gashcrumb @chirino

**Comment by gashcrumb** [comment]
@rhuss as far as the UI component goes we bring it in via a dependency in our package.json using the git repo.  We've an open issue in the UI now to switch over to the updated component.

**Comment by mattrpav** [comment]
Hi @rhuss -

As @gashcrumb mentioned, the datamapper-ui is designed to be an Angular2/4 module that the iPaaS imports. We have a lightweight Angular wrapper application around the datamapper-ui module for datamapper ui development purposes as well.

The open source community for data mapper bits is here: https://github.com/atlasmap

Currently, the datamapper-* repos in syndesis have the version of the datamapper code used for the RH Summit demo. The current plan we are operating under is that the upstream will be in atlasmap and then the syndesis specific bits will be in the syndesis repos.

In concrete terms:

atlasmap.io /
   - atlasmap (runtime engine, data format modules, design time services)
   - camel-atlasmap 
   - atlasmap-ui (Angular2/4 module and development wrapper application)

syndesis.io /
   - syndesis-datamapper
            + runtime (spring boot + docker image creation
            + syndesis.itests (integration tests specific to syndesis.. twitter to sfdc, etc)

  - syndesis-datamapper-ui
             + I believe this will be fully retired.  (I need @gashcrumb @jbakermd to confirm)

I'm always up for a call / virtual chat to discuss further as well.

**Comment by rhuss** [comment]
@mattrpav thanks for the clarification, this structure makes much sense.

**Pull request closed without merging**
